services:
  rclone-webui:
    image: rclone/rclone:latest
    container_name: rclone-webui
    user: "1000:1000"                 # UID:GID
    environment:
      - TZ=Europe/Madrid
      - XDG_CACHE_HOME=/config/rclone/.cache
    ports:
      - "5670:5670"                   # LAN: http://IP_DEL_HOST:5670
    volumes:
      - /rclone/config:/config/rclone # rclone.conf y caché WebUI
    command: >
      rcd
      --rc-addr=:5670
      --rc-user=admin
      --rc-pass=CAMBIA_ESTA_PASSWORD  # cambia esta contraseña
      --rc-web-gui
      --rc-web-gui-update
      --rc-web-gui-no-open-browser
      --log-level=INFO
    restart: unless-stopped
